version: '3.9'

services:
  eureka-server:
    image: ghcr.io/atulpatil-belgium/eureka-server-service:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-net
    restart: unless-stopped

  user-service:
    image: ghcr.io/atulpatil-belgium/user-service:latest
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - micro-net
    restart: unless-stopped

  order-service:
    image: ghcr.io/atulpatil-belgium/order-service:latest
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - micro-net
    restart: unless-stopped

  payment-service:
    image: ghcr.io/atulpatil-belgium/payment-service:latest
    container_name: payment-service
    ports:
      - "8083:8080"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - micro-net
    restart: unless-stopped

  notification-service:
    image: ghcr.io/atulpatil-belgium/notification-service:latest
    container_name: notification-service
    ports:
      - "8084:8080"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - micro-net
    restart: unless-stopped

networks:
  micro-net:
    driver: bridge
