spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0
      properties:
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        max.block.ms: 3000
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.common.serialization.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.common.serialization.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer


        
server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 

logging:
  level:
    '[org.springframework.kafka]': DEBUG     


resilience4j:
  circuitbreaker:
    instances:
      notificationBreakerService:
        register-health-indicator: true
        slidingWindowType: COUNT_BASED
        sliding-window-size: 3
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true