name: CI - Build user-service

on:
  push:
    branches: [ "main" ]
#    paths:
#      - 'user-service/**'
#      - 'order-service/**'
#      - 'payment-service/**'
#      - 'notification-service/**'
#     - 'eureka-server-service/**'

# jobs:
#   build-user-service:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v4

#       - name: Set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '21'

#       - name: Build Spring Boot application
#         working-directory: user-service
#         run: mvn clean package -DskipTests

#       - name: Build Docker image
#         working-directory: user-service
#         run: docker build -t user-service:latest .
#   build-order-service:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '21'

#       - name: Build order-service
#         working-directory: order-service
#         run: mvn clean package -DskipTests

#       - name: Docker build order-service
#         working-directory: order-service
#         run: docker build -t order-service:latest .
jobs:
  build:
    name: Build ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - order-service
          - payment-service
          - notification-service
          - eureka-server-service

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot application
        working-directory: ${{ matrix.service }}
        run: mvn clean package -DskipTests

      - name: Build Docker image
        working-directory: ${{ matrix.service }}
        run: docker build -t ${{ matrix.service }}:latest .